import{DB}from'./db.js';import{inspect,save,download,safe}from'./archive.js';import{PRESETS,apply,load,palette}from'./themes.js';import{catalog,norm,search,parseUrl,gxSearch,COMPONENTS}from'./gx.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const q=$('#q'),chips=$('#chips'),sort=$('#sort'),resolveInput=$('#resolveInput'),resolveBtn=$('#resolve'),openSearch=$('#openSearch'),gxStore=$('#gxStore'),random=$('#random'),themeJump=$('#themeJump'),chaos=$('#chaos'),chaosN=$('#chaosN'),fileInput=$('#fileInput'),drop=$('#drop'),accent=$('#accent'),second=$('#second'),bg=$('#bg'),glow=$('#glow'),radius=$('#radius'),mutateBtn=$('#mutate'),resetTheme=$('#resetTheme'),themeImage=$('#themeImage'),preferZip=$('#preferZip'),recordHistory=$('#recordHistory'),effects=$('#effects'),reduce=$('#reduce'),reloadCatalog=$('#reloadCatalog'),exportAll=$('#exportAll'),exportLib=$('#exportLib'),restore=$('#restore'),clearBtn=$('#clear'),install=$('#install');
const S={mods:[],meta:{},query:'',filter:'All',sort:'relevance',fav:new Set(),settings:{preferZip:true,recordHistory:true,effects:true,reduce:false},theme:load()};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),fmt=n=>n>999999?(n/1e6).toFixed(1)+'M':n>999?(n/1e3).toFixed(1)+'K':String(n||0),bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`};
function toast(t,e=false){const n=document.createElement('div');n.className='toast'+(e?' err':'');n.textContent=t;$('#toasts').append(n);setTimeout(()=>n.remove(),4300)}
function nav(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));history.replaceState(null,'','#'+id);if(id==='library')renderLibrary();if(id==='themes')renderThemes();if(id==='settings')diag()}
function card(m){const e=document.createElement('article');e.className='card';e.innerHTML=`<div class="art">${m.image?`<img loading="lazy" src="${esc(m.image)}" alt="">`:''}</div><div class="cardBody"><div class="cardTitle"><h3 title="${esc(m.name)}">${esc(m.name)}</h3><button class="fav ${S.fav.has(m.id)?'on':''}">${S.fav.has(m.id)?'♥':'♡'}</button></div><div class="author">${esc(m.author)}</div><div class="tags">${[...m.components,...m.tags].slice(0,4).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="meta"><span>${m.installs?fmt(m.installs)+' installs':'GX Store'}</span><span>${esc(m.size||m.version||'')}</span></div><div class="actions"><button class="details">Details</button><button class="primary dl">${m.packageUrl?'Download':'Open GX'}</button></div></div>`;e.querySelector('.fav').onclick=()=>favorite(m);e.querySelector('.details').onclick=()=>openMod(m);e.querySelector('.art').onclick=()=>openMod(m);e.querySelector('.dl').onclick=()=>getMod(m);return e}
function render(){const out=search(S.mods,S.query,S.filter,S.sort),g=$('#grid');g.innerHTML='';out.forEach(m=>g.append(card(m)));$('#count').textContent=`${out.length} mods`;$('#title').textContent=S.query?`Results for “${S.query}”`:S.filter==='All'?'GX Mods':S.filter;$('#label').textContent=S.query?'SEARCH':'DISCOVER';$('#empty').hidden=!!out.length}
async function favorite(m){if(S.fav.has(m.id)){S.fav.delete(m.id);await DB.del('favorites',m.id)}else{S.fav.add(m.id);await DB.put('favorites',{id:m.id,mod:m,at:new Date().toISOString()});await DB.put('library',{id:m.id,mod:m,at:new Date().toISOString()})}render();toast(S.fav.has(m.id)?'Added to favorites':'Removed from favorites');renderLibrary()}
async function renderLibrary(){const lib=await DB.all('library'),im=await DB.all('imports'),hist=await DB.all('history'),g=$('#libGrid');g.innerHTML='';const mods=[...lib.map(x=>norm(x.mod||x)),...im.map(x=>norm({id:x.id,name:x.name,author:'Local import',description:`${x.container}${x.version?' v'+x.version:''} • SHA-256 ${x.id.slice(0,16)}…`,tags:['Imported','Local'],size:bytes(x.size)}))];mods.forEach(m=>g.append(card(m)));$('#sSaved').textContent=lib.length;$('#sFav').textContent=S.fav.size;$('#sImp').textContent=im.length;$('#sHist').textContent=hist.length;$('#libCount').textContent=lib.length+im.length}
function openMod(m){const b=$('#modalBody');b.innerHTML=`<div class="detailArt">${m.image?`<img src="${esc(m.image)}" alt="">`:''}</div><div class="detail"><small class="eyebrow">${esc((m.components[0]||'GX MOD').toUpperCase())}</small><h2>${esc(m.name)}</h2><div class="author">${esc(m.author)} ${m.version?'• v'+esc(m.version):''} ${m.size?'• '+esc(m.size):''}</div><p>${esc(m.description||'GX Store mod. Catalog metadata will expand as the automated sync learns more about this package.')}</p><div class="tags">${[...m.components,...m.tags].map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><div class="detailBtns"><button class="primary" id="mainDl">${m.packageUrl?'Download package':'Open GX Store'}</button>${m.packageUrl?'<button id="rawZip">Raw ZIP</button><button id="copyUrl">Copy package URL</button>':''}${m.url?`<a href="${esc(m.url)}" target="_blank" rel="noopener">Official page ↗</a>`:''}</div></div>`;$('#modal').showModal();$('#mainDl').onclick=()=>getMod(m);if(m.packageUrl){$('#rawZip').onclick=()=>getMod(m,true);$('#copyUrl').onclick=async()=>{await navigator.clipboard.writeText(m.packageUrl);toast('Direct package URL copied')}}}
async function getMod(m,forceZip=false){if(!m.packageUrl){window.open(m.url||gxSearch(m.name),'_blank','noopener');return}const asZip=forceZip||S.settings.preferZip;try{const kind=await download(m,asZip);toast(`${kind.toUpperCase()} download started`);await remember(m,kind)}catch(e){if(asZip){toast(`Raw ZIP blocked: ${e.message}. Falling back to original CRX.`,true);try{await download(m,false);await remember(m,'crx')}catch(x){toast(x.message,true)}}else toast(e.message,true)}}
async function remember(m,kind){await DB.put('library',{id:m.id,mod:m,at:new Date().toISOString()});if(S.settings.recordHistory)await DB.put('history',{id:`${Date.now()}-${m.id}`,modId:m.id,name:m.name,kind,at:new Date().toISOString()});renderLibrary()}
function renderThemes(){const g=$('#themesGrid');g.innerHTML='';for(const t of PRESETS){const b=document.createElement('button');b.className='themeCard';b.style.setProperty('--pbg',t.bg);b.style.setProperty('--pa',t.accent);b.innerHTML=`<b>${esc(t.name)}</b><small>${esc(t.id)}</small>`;b.onclick=()=>{S.theme={...t};apply(S.theme);syncTheme()};g.append(b)}}
function syncTheme(){accent.value=S.theme.accent;second.value=S.theme.second;bg.value=S.theme.bg;glow.value=S.theme.glow??55;radius.value=S.theme.radius??18}
function mutate(){const h=()=>`#${Math.floor(Math.random()*0xffffff).toString(16).padStart(6,'0')}`;S.theme={...S.theme,id:'mutant',name:'Mutant',accent:h(),second:h(),glow:35+Math.floor(Math.random()*61),radius:7+Math.floor(Math.random()*25)};apply(S.theme);syncTheme()}
async function files(list){for(const f of list){try{const x=await inspect(f);await DB.put('imports',{id:x.id,name:x.name,size:x.size,container:x.container,version:x.version,offset:x.offset,at:new Date().toISOString()});const c=document.createElement('article');c.className='inspectCard';c.innerHTML=`<h3>${esc(x.name)}</h3><div class="facts"><div><small>Container</small><b>${x.container}${x.version?' v'+x.version:''}</b></div><div><small>File size</small><b>${bytes(x.size)}</b></div><div><small>ZIP offset</small><b>${x.offset} bytes</b></div><div><small>SHA-256</small><b title="${x.id}">${x.id.slice(0,16)}…</b></div></div><div class="actions"><button class="primary extract">Save raw ZIP</button></div>`;c.querySelector('.extract').onclick=()=>save(x.zip,`${safe(x.name.replace(/\.(crx|zip)$/i,''))}.zip`,'application/zip');$('#inspect').prepend(c);toast(`Inspected ${x.name}`)}catch(e){toast(`${f.name}: ${e.message}`,true)}}renderLibrary()}
function diag(){const m=S.meta||{};$('#diag').textContent=`Catalog entries: ${S.mods.length}\nGenerated: ${m.generatedAt||'bundled seed'}\nSources: ${(m.sources||['GX Store']).join(', ')}\nResolved package URLs: ${S.mods.filter(x=>x.packageUrl).length}\nService worker: ${'serviceWorker'in navigator?'supported':'unsupported'}\nIndexedDB: ${'indexedDB'in window?'supported':'unsupported'}\nFile API: ${'FileReader'in window?'supported':'unsupported'}`}
function syncSettings(){preferZip.checked=S.settings.preferZip;recordHistory.checked=S.settings.recordHistory;effects.checked=S.settings.effects;reduce.checked=S.settings.reduce;document.body.classList.toggle('reduced',S.settings.reduce);$('.ambient').hidden=!S.settings.effects}
async function setSetting(id,v){S.settings[id]=v;await DB.put('settings',{id,value:v});syncSettings()}
async function jsonDownload(o,name){const b=new TextEncoder().encode(JSON.stringify(o,null,2));save(b,name,'application/json')}
async function init(){for(const x of await DB.all('favorites'))S.fav.add(x.id);for(const x of await DB.all('settings'))if(x.id in S.settings)S.settings[x.id]=x.value;apply(S.theme);syncTheme();syncSettings();try{const c=await catalog();S.mods=c.mods;S.meta=c.meta;$('#dot').style.background='#5dff8b';$('#health').textContent=`${S.mods.length} synced mods`;render()}catch(e){$('#dot').style.background='#ff4668';$('#health').textContent='catalog unavailable';toast(e.message,true)}renderLibrary();diag()}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#close').onclick=()=>$('#modal').close();$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').close()};q.oninput=e=>{S.query=e.target.value;render()};q.onkeydown=e=>{if(e.key==='Enter'&&parseUrl(q.value)){resolveInput.value=q.value;resolveBtn.click()}};document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q.focus();q.select()}if(e.key==='Escape'&&$('#modal').open)$('#modal').close()});
for(const c of ['All',...COMPONENTS.slice(0,10)]){const b=document.createElement('button');b.className='chip'+(c==='All'?' active':'');b.textContent=c;b.onclick=()=>{S.filter=c;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));render()};chips.append(b)}sort.onchange=e=>{S.sort=e.target.value;render()};resolveBtn.onclick=()=>{const p=parseUrl(resolveInput.value);if(!p)return toast('That is not a GX Store mod URL.',true);const m=S.mods.find(x=>x.id===p.id||x.slug===p.slug);if(m)openMod(m);else{toast('Not in the synced catalog yet — opening official GX page');window.open(p.url,'_blank','noopener')}};openSearch.onclick=()=>window.open(gxSearch(S.query),'_blank','noopener');gxStore.onclick=()=>window.open('https://store.gx.me/mods/','_blank','noopener');random.onclick=()=>S.mods.length&&openMod(S.mods[Math.floor(Math.random()*S.mods.length)]);themeJump.onclick=()=>nav('themes');chaos.onclick=()=>{let n=(Number(chaosN.textContent)+25)%125;chaosN.textContent=n;if(n===0){S.theme={...PRESETS[0]};apply(S.theme);syncTheme()}else mutate();toast(n?`Chaos raised to ${n}`:'Chaos contained')};
fileInput.onchange=e=>files(e.target.files);for(const t of ['dragenter','dragover'])drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('drag')});for(const t of ['dragleave','drop'])drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',e=>files(e.dataTransfer.files));
for(const el of [accent,second,bg,glow,radius])el.oninput=()=>{S.theme={...S.theme,id:'custom',accent:accent.value,second:second.value,bg:bg.value,glow:Number(glow.value),radius:Number(radius.value)};apply(S.theme)};mutateBtn.onclick=()=>mutate();resetTheme.onclick=()=>{S.theme={...PRESETS[0]};apply(S.theme);syncTheme()};themeImage.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=await palette(f);S.theme={...S.theme,id:'asset-derived',name:`From ${f.name}`,...p};apply(S.theme);syncTheme();const u=URL.createObjectURL(f);document.body.style.backgroundImage=`linear-gradient(#0008,#000c),url(${u})`;document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed';toast('GX asset palette applied across the interface')}catch(x){toast(x.message,true)}};
preferZip.onchange=e=>setSetting('preferZip',e.target.checked);recordHistory.onchange=e=>setSetting('recordHistory',e.target.checked);effects.onchange=e=>setSetting('effects',e.target.checked);reduce.onchange=e=>setSetting('reduce',e.target.checked);reloadCatalog.onclick=()=>location.reload();exportAll.onclick=async()=>jsonDownload(await DB.export(),`gx-workshop-backup-${Date.now()}.json`);exportLib.onclick=async()=>jsonDownload({library:await DB.all('library'),favorites:await DB.all('favorites'),imports:await DB.all('imports')},`gx-workshop-library-${Date.now()}.json`);restore.onchange=async e=>{try{await DB.restore(JSON.parse(await e.target.files[0].text()));toast('Backup restored');setTimeout(()=>location.reload(),450)}catch(x){toast(x.message,true)}};clearBtn.onclick=async()=>{if(!confirm('Clear GX Workshop local data?'))return;for(const x of ['library','favorites','history','imports','themes','settings'])await DB.clear(x);localStorage.removeItem('gx-theme');location.reload()};
let prompt;addEventListener('beforeinstallprompt',e=>{e.preventDefault();prompt=e;install.hidden=false});install.onclick=async()=>{if(prompt){prompt.prompt();await prompt.userChoice;prompt=null;install.hidden=true}};if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));nav(location.hash.slice(1)||'browse');renderThemes();init();