import {DB} from './db.js';
import {inspect,save,safe} from './archive.js';
import {parseZip,extractEntry,mimeOf,kindOf,summary} from './zip.js';
const $=s=>document.querySelector(s), bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return`${x.toFixed(i?1:0)} ${u[i]}`};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(text,error=false){const n=document.createElement('div');n.className='toast'+(error?' err':'');n.textContent=text;$('#toasts')?.append(n);setTimeout(()=>n.remove(),4300)}
function jsonDownload(o,name){save(new TextEncoder().encode(JSON.stringify(o,null,2)),name,'application/json')}
function openText(title,text){$('#modalBody').innerHTML=`<div class="detail"><small class="eyebrow">WORKBENCH</small><h2>${esc(title)}</h2><pre class="manifestPre">${esc(String(text).slice(0,750000))}</pre></div>`;$('#modal').showModal()}
async function archiveFiles(list){for(const f of [...list]){try{const x=await inspect(f),z=parseZip(x.zip),sum=summary(z.entries);await DB.put('imports',{id:x.id,name:x.name,size:x.size,container:x.container,version:x.version,offset:x.offset,files:sum.files,at:new Date().toISOString()});const c=document.createElement('article');c.className='inspectCard enhancedInspect';c.innerHTML=`<h3>${esc(x.name)}</h3><div class="facts"><div><small>Container</small><b>${x.container}${x.version?' v'+x.version:''}</b></div><div><small>File size</small><b>${bytes(x.size)}</b></div><div><small>Files</small><b>${sum.files}</b></div><div><small>ZIP offset</small><b>${x.offset} bytes</b></div><div><small>SHA-256</small><b title="${x.id}">${x.id.slice(0,16)}…</b></div><div><small>Contents</small><b>${Object.entries(sum.kinds).map(([k,v])=>`${v} ${k}`).join(' • ')||'empty'}</b></div></div><div class="actions archiveActions"><button class="primary extractZip">Save raw ZIP</button><button class="report">Report JSON</button></div>`;c.querySelector('.extractZip').onclick=()=>save(x.zip,`${safe(x.name.replace(/\.(crx|zip)$/i,''))}.zip`,'application/zip');c.querySelector('.report').onclick=()=>jsonDownload({name:x.name,sha256:x.id,container:x.container,crxVersion:x.version,zipOffset:x.offset,summary:sum,entries:z.entries.map(({name,size,compressedSize,method,crc})=>({name,size,compressedSize,method,crc}))},`${safe(x.name)}-report.json`);const manifest=z.entries.find(e=>!e.directory&&/(^|\/)manifest\.json$/i.test(e.name));if(manifest){const b=document.createElement('button');b.textContent='View manifest';c.querySelector('.archiveActions').append(b);b.onclick=async()=>{try{openText(manifest.name,new TextDecoder().decode(await extractEntry(x.zip,manifest)))}catch(e){toast(e.message,true)}}}const fl=document.createElement('div');fl.className='fileList';for(const e of z.entries.filter(e=>!e.directory).slice(0,250)){const r=document.createElement('div');r.className='fileRow';r.innerHTML=`<span class="fileKind">${esc(kindOf(e.name).slice(0,3).toUpperCase())}</span><span title="${esc(e.name)}">${esc(e.name)}</span><small>${bytes(e.size)}</small><button>Extract</button>`;r.querySelector('button').onclick=async()=>{try{save(await extractEntry(x.zip,e),safe(e.name.split('/').pop()),mimeOf(e.name))}catch(err){toast(err.message,true)}};fl.append(r)}if(z.entries.length>250){const more=document.createElement('small');more.className='fileMore';more.textContent=`Showing first 250 of ${z.entries.length} entries`;fl.append(more)}c.append(fl);$('#inspect').prepend(c);toast(`Inspected ${x.name}: ${sum.files} files`)}catch(e){toast(`${f.name}: ${e.message}`,true)}}}
// Override the core file-picker path and intercept drop before the original lightweight handler.
const fileInput=$('#fileInput'),drop=$('#drop');if(fileInput)fileInput.onchange=e=>archiveFiles(e.target.files);if(drop)drop.addEventListener('drop',e=>{e.preventDefault();e.stopImmediatePropagation();drop.classList.remove('drag');archiveFiles(e.dataTransfer.files)},true);
