import {DB} from './db.js';
import {inspect,extract} from './archive.js';
import {parseZip,extractEntry,mimeOf,kindOf} from './zip.js';
import {apply,palette,derive} from './themes.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
function toast(text,error=false){const n=document.createElement('div');n.className='toast'+(error?' err':'');n.textContent=text;$('#toasts')?.append(n);setTimeout(()=>n.remove(),4300)}
let bgUrl=null,cardUrls=[];function themeBackground(blob){if(bgUrl)URL.revokeObjectURL(bgUrl);bgUrl=null;if(!blob){document.body.style.backgroundImage='';return}bgUrl=URL.createObjectURL(blob);document.body.style.backgroundImage=`linear-gradient(#05030888,#050308dc),url(${bgUrl})`;document.body.style.backgroundSize='cover';document.body.style.backgroundAttachment='fixed'}
function syncTheme(t){for(const [id,v] of Object.entries({accent:t.accent,second:t.second,bg:t.bg,glow:t.glow??55,radius:t.radius??18})){const e=$(`#${id}`);if(e)e.value=v}}
function activateTheme(t,preview=null,recordId=null){apply(t);syncTheme(t);themeBackground(preview);if(recordId)localStorage.setItem('gx-theme-record',recordId);else localStorage.removeItem('gx-theme-record')}
async function appendImportedThemes(){const grid=$('#themesGrid');if(!grid)return;cardUrls.forEach(u=>URL.revokeObjectURL(u));cardUrls=[];grid.querySelectorAll('.importedTheme').forEach(x=>x.remove());for(const rec of await DB.all('themes')){const t=rec.theme||rec,b=document.createElement('button');b.className='themeCard importedTheme';b.style.setProperty('--pbg',t.bg);b.style.setProperty('--pa',t.accent);if(rec.preview instanceof Blob){const u=URL.createObjectURL(rec.preview);cardUrls.push(u);b.style.backgroundImage=`linear-gradient(#05030855,#050308bb),url(${u})`;b.style.backgroundSize='cover';b.style.backgroundPosition='center'}b.innerHTML=`<b>${esc(t.name)}</b><small>${esc(t.style||t.id)}</small>`;b.onclick=()=>activateTheme(t,rec.preview instanceof Blob?rec.preview:null,rec.id);const d=document.createElement('span');d.className='themeDelete';d.textContent='×';d.title='Delete imported theme';d.onclick=async e=>{e.stopPropagation();await DB.del('themes',rec.id);if(localStorage.getItem('gx-theme-record')===rec.id)localStorage.removeItem('gx-theme-record');appendImportedThemes();toast('Imported theme removed')};b.append(d);grid.append(b)}}
const grid=$('#themesGrid');if(grid){const obs=new MutationObserver(()=>{if(!grid.querySelector('.importedTheme'))queueMicrotask(appendImportedThemes)});obs.observe(grid,{childList:true});appendImportedThemes()}
async function saveAssetTheme(blob,name,index){try{const colors=await palette(blob),t=derive(name,colors,index);await DB.put('themes',{id:t.id,theme:t,preview:blob,source:name,at:new Date().toISOString()});return 1}catch{return 0}}
async function scanThemeArchive(zipBytes,prefix='',depth=0,state={count:0,index:0}){if(depth>1||state.count>=120)return state;const z=parseZip(zipBytes);for(const e of z.entries.filter(x=>!x.directory)){if(state.count>=120)break;const kind=kindOf(e.name);if(kind==='image'&&e.size<=16*1024*1024){try{const raw=await extractEntry(zipBytes,e),blob=new Blob([raw],{type:mimeOf(e.name)});state.count+=await saveAssetTheme(blob,prefix+e.name,state.index++)}catch{}}else if(kind==='archive'&&depth<1&&e.size<=64*1024*1024){try{const raw=await extractEntry(zipBytes,e),inner=e.name.toLowerCase().endsWith('.crx')?extract(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength)).bytes:raw;await scanThemeArchive(inner,`${prefix}${e.name} → `,depth+1,state)}catch{}}}return state}
const themeInput=$('#themeImage');if(themeInput)themeInput.onchange=async e=>{let made=0,index=0;for(const f of [...e.target.files]){try{if(f.type.startsWith('image/')||/\.(png|jpe?g|webp|gif|svg|avif)$/i.test(f.name)){made+=await saveAssetTheme(f,f.name,index++)}else if(/\.(zip|crx)$/i.test(f.name)){const x=await inspect(f),state=await scanThemeArchive(x.zip,`${f.name} → `,0,{count:0,index});made+=state.count;index=state.index}}catch(err){toast(`${f.name}: ${err.message}`,true)}}await appendImportedThemes();toast(made?`Generated ${made} GX asset theme${made===1?'':'s'}`:'No usable image assets found',!made);e.target.value=''};
// Restore the selected imported theme/background after IndexedDB opens.
setTimeout(async()=>{const id=localStorage.getItem('gx-theme-record');if(!id)return;const rec=(await DB.all('themes')).find(x=>x.id===id);if(rec?.theme)activateTheme(rec.theme,rec.preview instanceof Blob?rec.preview:null,rec.id)},0);
