import fs from'node:fs/promises';
const ORIGIN='https://store.gx.me',MAX_PAGES=Number(process.env.MAX_PAGES||20),DETAIL_LIMIT=Number(process.env.DETAIL_LIMIT||400),UA='Mozilla/5.0 (compatible; GX-Workshop-Catalog/1.0; +https://github.com/Alastor-Kaneki/GX-Workshop)';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function get(url){for(let i=0;i<3;i++){const r=await fetch(url,{headers:{'user-agent':UA,accept:'text/html,application/xhtml+xml'}});if(r.ok)return r.text();if(r.status===429||r.status>=500){await sleep(900*(i+1));continue}throw Error(`${r.status} ${url}`)}throw Error(`failed ${url}`)}
const strip=s=>String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#x27;/g,"'").replace(/\s+/g,' ').trim();
function links(html){const m=new Map();for(const x of html.matchAll(/href=["'](?:https:\/\/store\.gx\.me)?\/mods\/([a-z0-9]+)\/([^"'/?#]+)\/?["']/gi))m.set(x[1],{id:x[1],slug:x[2],url:`${ORIGIN}/mods/${x[1]}/${x[2]}/`});for(const x of html.matchAll(/\\?["'](?:href\\?["']:\\?["'])?\/mods\/([a-z0-9]+)\/([^\\\"'/?#]+)\/?/gi)){const slug=x[2].replace(/\\.*$/,'');m.set(x[1],{id:x[1],slug,url:`${ORIGIN}/mods/${x[1]}/${slug}/`})}return[...m.values()]}
const pick=(h,re)=>{const m=h.match(re);return m?strip(m[1]):''};
function field(text,label,next){const i=text.indexOf(label);if(i<0)return'';const p=text.slice(i+label.length,i+label.length+240),ends=next.map(x=>p.indexOf(x)).filter(x=>x>=0).sort((a,b)=>a-b);return(ends.length?p.slice(0,ends[0]):p).trim()}
const COMPONENTS=['App icon','Background Music','Browser Sounds','Cursors','Fonts','Game Strip','Icons','Keyboard sounds','Mobile Icons','SD effects','Shader','Splash screen','Stickers','Theme','Wallpaper','Web Modding'];
function packageUrl(html){const d=html.replace(/\\u0026/g,'&').replace(/\\\//g,'/').replace(/&amp;/g,'&');for(const m of d.matchAll(/https:\/\/(?:mods\.store\.gx\.me|play\.gxc\.gg)\/mods\/[^\s"'<>\\]+/gi)){try{const u=new URL(m[0].replace(/[),.;}\]]+$/g,'')),p=u.pathname.split('/').filter(Boolean);if(p.at(-1)==='mod.crx'&&p.length>=5){u.search='';u.hash='';return u.href}const k=p.findIndex(x=>x==='contents'||x==='icons');if(k>=4){u.pathname='/'+p.slice(0,k).concat('mod.crx').join('/');u.search='';u.hash='';return u.href}}catch{}}return null}
async function detail(base){try{const html=await get(base.url),text=strip(html);const title=pick(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i)||pick(html,/<title[^>]*>([\s\S]*?)<\/title>/i).replace(/\s*[-|–].*GX Store.*$/i,'')||base.slug.replace(/-/g,' ');const desc=pick(html,/<meta[^>]+(?:name|property)=["'](?:description|og:description)["'][^>]+content=["']([^"']*)/i);const image=pick(html,/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']*)/i);const components=COMPONENTS.filter(c=>text.includes(c));const version=field(text,'Version',['Installs','Size','Image']);const installs=Number((field(text,'Installs',['Size','Image']).match(/[\d,]+/)?.[0]||'0').replace(/,/g,''));const size=field(text,'Size',['Image','English']).split(' ').slice(0,2).join(' ');const updatedAt=field(text,'Last update',['Version','Installs','Size']);let author='Unknown studio';const sm=text.match(/([A-Za-z0-9_.'’ -]{2,60}\s+studio)\s+(?:Date created|#|$)/i);if(sm)author=sm[1].trim();return{...base,name:title,author,description:desc,image,components,tags:[],version,installs,size,updatedAt,packageUrl:packageUrl(html)}}catch(e){console.warn('detail failed',base.url,e.message);return{...base,name:base.slug.replace(/-/g,' '),author:'Unknown studio',description:'',image:'',components:[],tags:[],version:'',installs:0,size:'',updatedAt:'',packageUrl:null}}}
const found=new Map();for(const suffix of['','&sort=last-modified-desc'])for(let page=0;page<MAX_PAGES;page++){const url=`${ORIGIN}/mods/?page=${page}${suffix}`;console.log('scan',url);try{for(const x of links(await get(url)))found.set(x.id,x)}catch(e){console.warn(e.message);break}await sleep(120)}
const list=[...found.values()].slice(0,DETAIL_LIMIT),mods=[];let cursor=0;async function worker(){while(cursor<list.length){const i=cursor++;mods[i]=await detail(list[i]);await sleep(90)}}await Promise.all(Array.from({length:6},worker));mods.sort((a,b)=>(b.installs||0)-(a.installs||0));const out={meta:{generatedAt:new Date().toISOString(),sources:['GX Store official pages'],pagesPerSort:MAX_PAGES,entries:mods.length},mods};await fs.mkdir('data',{recursive:true});await fs.writeFile('data/catalog.json',JSON.stringify(out,null,2)+'\n');console.log(`wrote ${mods.length} mods; resolved ${mods.filter(x=>x.packageUrl).length} package URLs`);
